// Canonical account codes. Keep in sync with drizzle/0002_seed_chart.sql.

export const A = {
  CUSTOMER_FUNDING_USD:     'CUSTOMER_FUNDING_USD',
  CUSTOMER_FUNDING_EUR:     'CUSTOMER_FUNDING_EUR',
  AUTHORIZATION_HOLD_USD:   'AUTHORIZATION_HOLD_USD',
  AUTHORIZATION_HOLD_EUR:   'AUTHORIZATION_HOLD_EUR',
  PROCESSOR_RECEIVABLE_USD: 'PROCESSOR_RECEIVABLE_USD',
  PROCESSOR_RECEIVABLE_EUR: 'PROCESSOR_RECEIVABLE_EUR',
  STRIPE_CASH_USD:          'STRIPE_CASH_USD',
  STRIPE_CASH_EUR:          'STRIPE_CASH_EUR',
  MERCHANT_PAYABLE_USD:     'MERCHANT_PAYABLE_ACME_USD',
  MERCHANT_PAYABLE_EUR:     'MERCHANT_PAYABLE_ACME_EUR',
  STRIPE_FEE_REVENUE_USD:   'STRIPE_FEE_REVENUE_USD',
  STRIPE_FX_REVENUE_USD:    'STRIPE_FX_REVENUE_USD',
  DISPUTE_RESERVE_USD:      'DISPUTE_RESERVE_USD',
  REFUND_CLEARING_USD:      'REFUND_CLEARING_USD',
  FX_CLEARING_USD:          'FX_CLEARING_USD',
  FX_CLEARING_EUR:          'FX_CLEARING_EUR',
  CHARGEBACK_LOSS_USD:      'CHARGEBACK_LOSS_USD',
} as const;

export type AccountCode = typeof A[keyof typeof A];
